In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
np.array([1, 2, 3])

array([1, 2, 3])

In [4]:
print(np.array([1, 2, 3]))

[1 2 3]


In [6]:
print(np.array([[1, 2, 3], [4, 5, 6]]))

[[1 2 3]
 [4 5 6]]


In [10]:
# 빈 array 생성하기
print(np.empty(5)) # 인자로 shape를 넘겨준다

[ 0.  0.  0.  0.  0.]


In [9]:
print(np.empty((5, 4))) # 튜플로 shape을 넘겨준다

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [13]:
print(np.ones(5)) # 1로 초기화된 array 생성

[ 1.  1.  1.  1.  1.]


In [14]:
# float형이 아닌 int 형으로 만들고 싶으면
print(np.ones(5, dtype=np.int))

[1 1 1 1 1]


In [18]:
# random array 생성하기
print(np.random.random((5, 4)))

[[ 0.58248773  0.17522745  0.35409618  0.09302626]
 [ 0.06882504  0.87445446  0.13475956  0.66925665]
 [ 0.82065335  0.33754456  0.41412714  0.50339663]
 [ 0.30487476  0.9095      0.35099068  0.65822205]
 [ 0.25220395  0.37821724  0.80003666  0.24965485]]


In [19]:
print(np.random.rand(5,4))

[[ 0.69935927  0.59157237  0.15666669  0.41701777]
 [ 0.23560076  0.68140513  0.65678503  0.73004023]
 [ 0.03685924  0.77151724  0.26588665  0.77132218]
 [ 0.62955974  0.66069103  0.24178259  0.02291089]
 [ 0.80870745  0.95958937  0.28670644  0.89163211]]


In [28]:
# 정규분포
print(np.random.normal(50, 10, size=(2,3))) # 평균 50 표준편차 10

[[ 49.03197421  65.02160877  45.60856084]
 [ 54.71121742  53.92564284  34.5095406 ]]


In [29]:
np.random.normal(size=(2,3)) # 평균 0, 표준편차 1

array([[-0.50565176, -0.18519916, -1.54362555],
       [-0.24915023,  0.2455869 , -0.12036906]])

In [31]:
# 랜덤 범위 0 ~ 5설정
np.random.randint(0, 5) 

1

In [34]:
np.random.randint(0, 5, size=(2, 3)) # 0 ~ 5까지 랜덤 2행 3열

array([[4, 0, 2],
       [3, 4, 1]])

In [40]:
# array 의 shape 속성은 튜플을 준다.

In [41]:
arr = np.random.random((5, 4))

In [42]:
arr.shape

(5, 4)

In [43]:
arr.shape[0] # 행의 개수
arr.shape[1] # 열의 개수

4

In [44]:
len(arr.shape) # arr.shape은 튜플이다. 튜플의 len은 차원을 알려준다

2

In [45]:
arr.size # size 속성은 요소의 개수를 반환한다.

20

In [46]:
np.random.seed(639)

In [55]:
n = np.random.randint(0, 10, size=(5,4))

In [56]:
n.sum()

87

In [57]:
print(n)

[[1 3 0 3]
 [7 6 5 9]
 [0 5 2 0]
 [8 3 9 8]
 [7 2 1 8]]


In [58]:
n.sum(axis=0) # sum of rows

array([23, 19, 17, 28])

In [59]:
n.sum(axis=1) # sum of columns

array([ 7, 27,  7, 28, 18])

In [61]:
# array로 array를 인덱싱 하기

In [64]:
a = np.random.rand(5)

In [65]:
a

array([ 0.70949835,  0.79068833,  0.45757132,  0.51446198,  0.10087438])

In [66]:
idx = np.array([1, 1, 2, 4])

In [67]:
idx

array([1, 1, 2, 4])

In [68]:
a[idx]

array([ 0.79068833,  0.79068833,  0.45757132,  0.10087438])

In [69]:
arr = np.random.randint(0, 10, size=(2, 5))

In [70]:
arr

array([[2, 3, 0, 6, 0],
       [0, 6, 8, 7, 3]])

In [71]:
arr.mean()

3.5

In [73]:
arr[arr<arr.mean()] #masking

array([2, 3, 0, 0, 0, 3])

In [74]:
arr[arr<arr.mean()] = arr.mean()

In [76]:
arr

array([[3, 3, 3, 6, 3],
       [3, 6, 8, 7, 3]])

In [77]:
arr.dtype

dtype('int64')

In [78]:
arr.dtype = np.float

In [91]:
arr = np.array([(1, 2, 3), (10, 20, 30)])

In [92]:
arr2 = np.array([(10, 20, 30), (20, 40, 60)],dtype=np.int)

In [96]:
arr.dtype

dtype('int64')

In [97]:
arr2.dtype

dtype('int64')